#!/bin/bash

# In a temp folder, create a folder called lacie-uboot-0.1
# make a tar lacie-uboot_0.1.orig.tar.gz
# execute debuild a first time

VERSION=1.0
actual_dir=$(pwd)
work_dir=$(mktemp -d)

pushd $work_dir &> /dev/null
cp -R $actual_dir/ ./lacie-uboot-${VERSION}
rm -rf ./lacie-uboot-${VERSION}/.git
tar czf lacie-uboot_${VERSION}.orig.tar.gz lacie-uboot-${VERSION}
pushd $work_dir/lacie-uboot-${VERSION} &>/dev/null
#debuild -uc -us --source-option=--include-binaries --source-option=-isession
debuild -sa
popd &> /dev/null
#lacie_uboot_path=$(ls lacie-uboot*.deb)
#mv $(pwd)/${lacie_uboot_path} $actual_dir
#echo -e "\033[32mDebian package available at ${actual_dir}/${lacie_uboot_path}"
popd &> /dev/null

echo "$work_dir"

# Cleaning time
#[ -d "$work_dir" ] && rm -Rf $work_dir

