.TH LACIE-UBOOT-SHELL 1 "2012 Dec 26"
.SH NAME
lacie-uboot-shell \- Access LaCie NAS U-Boot netconsole with no hardware
.SH SYNOPSIS
.br
.B lacie-uboot-shell
[options]
.SH DESCRIPTION
.B lacie-uboot-shell
A simple interactive client which can connect to the U-Boot netconsole using
only a network cable.
By default, it uses the port 6666, 4445 and 4446.
.PP
.SH OPTIONS
The options may be given in any order.
.br
.TP 15
\-h, \-\-help
Display
.B lacie-uboot-shell
help, options and usage.
.TP
.RB \-i " IFACE", " " \-\-iface= "IFACE"
Give
.B lacie-uboot-shell
the IFACE you want to use to communicate with the device.
.TP
.RB \-m " MAC", " " \-\-mac= "MAC"
Give
.B lacie-uboot-shell
the MAC address of the target. It must be in the 00:00:00:00:00:00 format where
each hexadecimal number is > 0 and < F.
.TP
.RB \-\-ip " FORCE_IP"
Specify the IP address to assign to the device.
.RB \-p, \-\-progress
Use this option with a
.B lacie-uboot-shell
script.
This option will discard the output and print a progress bar
to show the progress of the script.
.TP
.RB \-w, \-\-wait
Use this option if you want to wait for the product to be online.
This option use IPCONF protocol to detect the product's presence.
.TP
.RB \-D, \-\-debug
Output debug informations.
.SH SEE ALSO
nc(1)
.SH AUTHORS
.B lacie-uboot-shell
is written and maintained by Maxime Hadjinlian <maxime.hadjinlian@gmail.com>,
with help from a few others. See the AUTHORS file for more information.
